# Generated by Django 4.1.4 on 2022-12-29 12:25

import Home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=200)),
                ('Problem', models.TextField(default='Hello World')),
            ],
        ),
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=250)),
                ('Profile_pic', Home.models.CloudinaryField(max_length=255, verbose_name='Profile_Pic')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Done', models.IntegerField(default=0)),
                ('Prblm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.codeprob')),
            ],
        ),
        migrations.AddField(
            model_name='codeprob',
            name='Writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.userprof'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScrSht', Home.models.CloudinaryField(max_length=255, verbose_name='Screen Shot')),
                ('Author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.userprof')),
                ('Problem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.codeprob')),
            ],
        ),
    ]
