# Generated by Django 4.1.4 on 2023-01-01 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_remove_userprof_user_userprof_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='User',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
