# Generated by Django 4.1.4 on 2023-01-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_userprof_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='Done',
        ),
        migrations.AddField(
            model_name='status',
            name='UserAsg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.userprof'),
        ),
    ]
