# Generated by Django 4.1.4 on 2023-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_status_done_status_userasg'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Sts',
            field=models.IntegerField(default=0),
        ),
    ]
